version: '3.8'

services:
  fku-si:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fku-si
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    environment:
      - TZ=Asia/Seoul 